const express = require("express");
const router = express.Router();
const ic = require("../controllers/inventoryController");
router.get("/categories", ic.getCategories);
router.get("/", ic.getAll);
router.get("/:id", ic.getById);
router.post("/", ic.create);
router.put("/:id", ic.update);
router.delete("/:id", ic.delete);
module.exports = router;
